<a href="https://colab.research.google.com/github/nishantsingh23pbt/AdvanceHousePrice_MultipleRegression/blob/main/MLDLS2021_Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing all necessary libraries required.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
dataset=pd.read_csv('train2.csv')

#print shape of dataset with rows and columns
print(dataset.shape)

(1460, 81)

In [3]:
dataset.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [31]:
X = dataset[['OverallQual'	,'OverallCond']]
Y = dataset['SalePrice']
X

      OverallQual  OverallCond
0               7            5
1               6            8
2               7            5
3               7            5
4               8            5
...           ...          ...
1455            6            5
1456            6            6
1457            7            9
1458            5            6
1459            5            6

[1460 rows x 2 columns]

In [32]:
Y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)
print(X_train.shape, X_test.shape)

(1022, 2) (438, 2)

In [42]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [44]:
accuracy=model.score(X,Y)
print(accuracy)

0.6256785279481476

In [50]:


predicted = model.predict([[23, 13]])
print(predicted)

[945607.63789765]